"""empty message

Revision ID: 3297dd286f73
Revises: eb1a68d734ae
Create Date: 2020-10-17 00:46:51.392409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3297dd286f73'
down_revision = 'eb1a68d734ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('class1', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('department', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('division', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('division_name', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('subclass1', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('upc', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'products', ['upc'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'upc')
    op.drop_column('products', 'subclass1')
    op.drop_column('products', 'division_name')
    op.drop_column('products', 'division')
    op.drop_column('products', 'department')
    op.drop_column('products', 'class1')
    # ### end Alembic commands ###
