"""empty message

Revision ID: 3b7019823f81
Revises: 68f4c0e5b9ba
Create Date: 2020-10-17 13:23:37.787075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7019823f81'
down_revision = '68f4c0e5b9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('upc', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'upc')
    # ### end Alembic commands ###
