"""empty message

Revision ID: 68f4c0e5b9ba
Revises: a524f430c1ad
Create Date: 2020-10-17 13:21:52.762692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f4c0e5b9ba'
down_revision = 'a524f430c1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_upc_key', 'products', type_='unique')
    op.drop_column('products', 'upc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('upc', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('products_upc_key', 'products', ['upc'])
    # ### end Alembic commands ###
