"""Add missing sku desc

Revision ID: 86e5f664bd3e
Revises: 9b0be35a6f1a
Create Date: 2020-10-17 15:01:27.480552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e5f664bd3e'
down_revision = '9b0be35a6f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.BigInteger(), nullable=False),
    sa.Column('upc', sa.BigInteger(), nullable=True),
    sa.Column('sku_desc', sa.String(length=120), nullable=True),
    sa.Column('style_desc', sa.String(length=120), nullable=False),
    sa.Column('style_option', sa.String(length=120), nullable=False),
    sa.Column('colour_name', sa.String(length=120), nullable=False),
    sa.Column('size_code', sa.String(length=120), nullable=False),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('division_name', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('department_name', sa.String(length=120), nullable=True),
    sa.Column('class1', sa.String(length=120), nullable=True),
    sa.Column('class_name', sa.String(length=120), nullable=True),
    sa.Column('subclass1', sa.String(length=120), nullable=True),
    sa.Column('subclass_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_style_option'), 'products', ['style_option'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_style_option'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
