"""products table

Revision ID: eb1a68d734ae
Revises: 
Create Date: 2020-10-16 22:42:46.606801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1a68d734ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.BigInteger(), nullable=False),
    sa.Column('style_desc', sa.String(length=120), nullable=False),
    sa.Column('style_option', sa.String(length=120), nullable=False),
    sa.Column('colour_name', sa.String(length=120), nullable=False),
    sa.Column('size_code', sa.String(length=120), nullable=False),
    sa.Column('department_name', sa.String(length=120), nullable=True),
    sa.Column('class_name', sa.String(length=120), nullable=True),
    sa.Column('subclass_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_style_option'), 'products', ['style_option'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_style_option'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
